(md) script to prepare and production ready

diff --git a/md/prepareMD b/md/prepareMD
--- a/md/prepareMD
+++ b/md/prepareMD
@@ -21,12 +21,14 @@ checkDependency() {
     command -v $1 >/dev/null 2>&1 || { echo >&2 "I require $1 but it's not installed.  Aborting."; exit 1; }
 }
 
+checkFile() {
+    [ -f $1 ] || { echo >&2 "Error: File $1 is not found.  Aborting."; exit 1; }
+}
 
-handleError() {
-    if [ $1 -ne 0 ]; then
-        echo "Error occurred in $2" >&2
-        exit $1
-    fi
+checkFiles() {
+    for file in "$@"; do
+        checkFile $file
+    done
 }
 
 createMDP () {
@@ -66,6 +68,9 @@ ref-t                   = 293 293
 ; Bond constraints
 constraints             = h-bonds
 constraint-algorithm    = LINCS 
+
+; Center of mass
+comm-mode               = None
 EOF
 }
 
@@ -111,66 +116,68 @@ EOF
 
 convertPDBToGROMACS() {
     gmx pdb2gmx -f "$input.pdb" -o protein_processed.gro -p topol.top -i posre.itp -posrefc 1000 -ff charmm36-jul2022 -water tip3p -ignh -nobackup
-    [ -f posre.itp ] || exit 1
-    [ -f topol.top ] || exit 1
-    [ -f protein_processed.gro ] || exit 1
+    checkFiles protein_processed.gro topol.top posre.itp
 }
 
 
 defineSimulationBox() {
     gmx editconf -f protein_processed.gro -o protein_newbox.gro -c -d 1.5 -bt cubic -nobackup
-    [ -f protein_newbox.gro ] || exit 1   
+    checkFiles protein_newbox.gro
 }
 
 
 solvateSystem() {
     gmx solvate -cp protein_newbox.gro -cs spc216.gro -o protein_solv.gro -p topol.top -nobackup
-    [ -f protein_solv.gro ] || exit 1
+    checkFiles protein_solv.gro
 }
 
 
 addIons() {
     touch ions.mdp
-    [ -f ions.mdp ] || exit 1
+    checkFile ions.mdp
 
     gmx grompp -f ions.mdp -c protein_solv.gro -o ions.tpr -p topol.top
-    [ -f ions.tpr ] || exit 1
+    checkFile ions.tpr
 
     gmx genion -s ions.tpr -o solv_ions.gro -p topol.top -pname NA -nname CL -conc 0.15 -neutral -nobackup <<< "SOL"
-    [ -f solv_ions.gro ] || exit 1
+    checkFile solv_ions.gro
 }
 
 
 energyMinimization() {
     cat > em.mdp << EOF
+; Run parameters
 integrator      = steep     ; Steepest descent minimization
 emtol           = 100.0     ; Tolerance for energy minimization
 emstep          = 0.01      ; Minimization step size
 nsteps          = 10000     ; Max steps for energy minimization
+
+; Non-bonded parameters
+cutoff-scheme   = Verlet    ; Use Verlet list for neighbor search
 nstlist         = 10        ; Update neighbor list every step
 rlist           = 1.2       ; Cut-off for making neighbor list (short range forces)
-cutoff-scheme   = Verlet    ; Use Verlet list for neighbor search
 ns-type         = grid      ; Grid search for neighbor list
+rvdw            = 1.2       ; Cut-off for Van der Waals interactions in nm
+
+; Electrostatics
 coulombtype     = PME       ; Particle Mesh Ewald for long-range electrostatics
 rcoulomb        = 1.2       ; Cut-off for Coulomb interactions in nm
-rvdw            = 1.2       ; Cut-off for Van der Waals interactions in nm
+DispCorr        = no
+
+; Bond constraints
 constraints     = h-bonds 
 constraint-algorithm = LINCS 
-DispCorr        = no
 EOF
-    [ -f em.mdp ] || exit 1
+    checkFile em.mdp
 
     gmx grompp -f em.mdp -c solv_ions.gro -p topol.top -o em.tpr
-    [ -f em.tpr ] || exit 1
+    checkFile em.tpr
 
     gmx mdrun -deffnm em -nb gpu
-    [ -f em.gro ] || exit 1
-    [ -f em.edr ] || exit 1
-    [ -f em.trr ] || exit 1
-    [ -f em.log ] || exit 1
+    checkFiles em.gro em.edr em.trr em.log
 
     gmx energy -f em.edr -o em_potential.xvg -xvg none -nobackup <<< $'Potential\n0\n'
-    [ -f em_potential.xvg ] || exit 1
+    checkFile em_potential.xvg
     
 }
 
@@ -179,21 +186,16 @@ nvtEquilibration() {
     createMDP nvt.mdp
     addPositionRestraints nvt.mdp
     setupSimulationMode nvt.mdp start
-    [ -f nvt.mdp ] || exit 1
+    checkFile nvt.mdp
 
     gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr
-    [ -f nvt.tpr ] || exit 1
+    checkFile nvt.tpr
 
     gmx mdrun -deffnm nvt -nb gpu
-    [ -f nvt.log ] || exit 1
-    [ -f nvt.trr ] || exit 1
-    [ -f nvt.edr ] || exit 1
-    [ -f nvt.xtc ] || exit 1
-    [ -f nvt.gro ] || exit 1
-    [ -f nvt.cpt ] || exit 1
+    checkFiles nvt.log nvt.trr nvt.edr nvt.xtc nvt.gro nvt.cpt
 
     gmx energy -f nvt.edr -o nvt_temperature.xvg -xvg none -nobackup <<< $'Temperature\n0\n'
-    [ -f nvt_temperature.xvg ] || exit 1
+    checkFile nvt_temperature.xvg
 }
 
 
@@ -202,125 +204,114 @@ nptEquilibration() {
     addPositionRestraints npt.mdp
     addPressureCoupling npt.mdp
     setupSimulationMode npt.mdp continue
-    [ -f npt.mdp ] || exit 1
+    checkFile npt.mdp
 
     gmx grompp -f npt.mdp -c nvt.gro -t nvt.cpt -r em.gro -p topol.top -o npt.tpr
-    [ -f npt.tpr ] || exit 1
+    checkFile npt.tpr
 
     gmx mdrun -deffnm npt -nb gpu
-    [ -f npt.log ] || exit 1
-    [ -f npt.trr ] || exit 1
-    [ -f npt.xtc ] || exit 1
-    [ -f npt.edr ] || exit 1
-    [ -f npt.gro ] || exit 1
-    [ -f npt.cpt ] || exit 1
+    checkFiles npt.log npt.trr npt.edr npt.xtc npt.gro npt.cpt
 
     gmx energy -f npt.edr -o npt.xvg -xvg none -nobackup <<< $'Pressure\nDensity\nPosition-Rest\nPotential\n0\n'
-    [ -f npt.xvg ] || exit 1
+    checkFile npt.xvg
 }
 
 
 eliminateRestraints() {
-    createMDP rst.mdp
-    addPositionRestraints rst.mdp
-    addPressureCoupling rst.mdp
-    setupSimulationMode rst.mdp continue
-    [ -f rst.mdp ] || exit 1
+    createMDP rst200.mdp
+    addPositionRestraints rst200.mdp
+    addPressureCoupling rst200.mdp
+    setupSimulationMode rst200.mdp continue
+    checkFile rst200.mdp
 
     sed -i 's/1000/200/g' posre.itp 
 
-    gmx grompp -f rst.mdp -c npt.gro -t npt.cpt -r em.gro -p topol.top -o rst_200.tpr
-    [ -f rst_200.tpr ] || exit 1
+    gmx grompp -f rst200.mdp -c npt.gro -t npt.cpt -r em.gro -p topol.top -o rst_200.tpr
+    checkFile rst_200.tpr
 
     gmx mdrun -deffnm rst_200 -nb gpu
-    [ -f rst_200.log ] || exit 1
-    [ -f rst_200.edr ] || exit 1
-    [ -f rst_200.trr ] || exit 1
-    [ -f rst_200.xtc ] || exit 1
-    [ -f rst_200.gro ] || exit 1
-    [ -f rst_200.cpt ] || exit 1
+    checkFiles rst_200.log rst_200.edr rst_200.trr rst_200.xtc rst_200.gro rst_200.cpt
 
     gmx energy -f rst_200.edr -o rst_200.xvg -xvg none -nobackup <<< $'Pressure\nDensity\nPosition-Rest\nPotential\n0\n'
-    [ -f rst_200.xvg ] || exit 1
+    checkFile rst_200.xvg
 
+
+    createMDP rst50.mdp
+    addPositionRestraints rst50.mdp
+    addPressureCoupling rst50.mdp
+    setupSimulationMode rst50.mdp continue
+    checkFile rst50.mdp
 
     sed -i 's/200/50/g' posre.itp 
-    gmx grompp -f rst.mdp -c rst_200.gro -t rst_200.cpt -r em.gro -p topol.top -o rst_50.tpr
-    [ -f rst_50.tpr ] || exit 1
+
+    gmx grompp -f rst50.mdp -c rst_200.gro -t rst_200.cpt -r em.gro -p topol.top -o rst_50.tpr
+    checkFile rst_50.tpr
 
     gmx mdrun -deffnm rst_50 -nb gpu
-    [ -f rst_50.log ] || exit 1
-    [ -f rst_50.edr ] || exit 1
-    [ -f rst_50.trr ] || exit 1
-    [ -f rst_50.xtc ] || exit 1
-    [ -f rst_50.gro ] || exit 1
-    [ -f rst_50.cpt ] || exit 1
+    checkFiles rst_50.log rst_50.edr rst_50.trr rst_50.xtc rst_50.gro rst_50.cpt
 
     gmx energy -f rst_50.edr -o rst_50.xvg -xvg none -nobackup <<< $'Pressure\nDensity\nPosition-Rest\nPotential\n0\n'
-    [ -f rst_50.xvg ] || exit 1
+    checkFile rst_50.xvg
 
+
+    createMDP rst10.mdp
+    addPositionRestraints rst10.mdp
+    addPressureCoupling rst10.mdp
+    setupSimulationMode rst10.mdp continue
+    checkFile rst10.mdp
 
     sed -i 's/50/10/g' posre.itp 
-    gmx grompp -f rst.mdp -c rst_50.gro -t rst_50.cpt -r em.gro -p topol.top -o rst_10.tpr
-    [ -f rst_10.tpr ] || exit 1
+
+    gmx grompp -f rst10.mdp -c rst_50.gro -t rst_50.cpt -r em.gro -p topol.top -o rst_10.tpr
+    checkFile rst_10.tpr
 
     gmx mdrun -deffnm rst_10 -nb gpu
-    [ -f rst_10.log ] || exit 1
-    [ -f rst_10.edr ] || exit 1
-    [ -f rst_10.trr ] || exit 1
-    [ -f rst_10.xtc ] || exit 1
-    [ -f rst_10.gro ] || exit 1
-    [ -f rst_10.cpt ] || exit 1
+    checkFiles rst_10.log rst_10.edr rst_10.trr rst_10.xtc rst_10.gro rst_10.cpt
 
     gmx energy -f rst_10.edr -o rst_10.xvg -xvg none -nobackup <<< $'Pressure\nDensity\nPosition-Rest\nPotential\n0\n'
-    [ -f rst_10.xvg ] || exit 1
+    checkFile rst_10.xvg
 
 
-    createMDP rst.mdp
-    addPressureCoupling rst.mdp
-    setupSimulationMode rst.mdp continue
-    gmx grompp -f rst.mdp -c rst_10.gro -t rst_10.cpt -p topol.top -o rst_0.tpr -maxwarn 1 #Warning with center of mass removal
-    [ -f rst_0.tpr ] || exit 1
+    createMDP rst0.mdp
+    addPressureCoupling rst0.mdp
+    setupSimulationMode rst0.mdp continue
+    checkFile rst0.mdp
+
+    gmx grompp -f rst0.mdp -c rst_10.gro -t rst_10.cpt -p topol.top -o rst_0.tpr -maxwarn 1 #Warning with center of mass removal
+    checkFile rst_0.tpr
 
     gmx mdrun -deffnm rst_0 -nb gpu
-    [ -f rst_0.log ] || exit 1
-    [ -f rst_0.edr ] || exit 1
-    [ -f rst_0.trr ] || exit 1
-    [ -f rst_0.xtc ] || exit 1
-    [ -f rst_0.gro ] || exit 1
-    [ -f rst_0.cpt ] || exit 1
+    checkFiles rst_0.log rst_0.edr rst_0.trr rst_0.xtc rst_0.gro rst_0.cpt
 
     gmx energy -f rst_0.edr -o rst_0.xvg -xvg none -nobackup <<< $'Pressure\nDensity\n0\n'
-    [ -f rst_0.xvg ] || exit 1
+    checkFile rst_0.xvg
+}
+
+shortFreeMD() {
+    createMDP md.mdp
+    setupSimulationMode md.mdp continue
+    checkFile md.mdp
+
+    gmx grompp -f md.mdp -c rst_0.gro -t rst_0.cpt -p topol.top -o md.tpr  -maxwarn 1 #Warning with center of mass removal
+    checkFile md.tpr
+
+    gmx mdrun -deffnm md -nb gpu
+    checkFiles md.log md.edr md.trr md.xtc md.gro md.cpt
+
+    gmx energy -f md.edr -o md.xvg -xvg none -nobackup <<< $'Pressure\n0\n'
+    checkFile md.xvg
 }
 
 checkDependency "gmx"
 
 convertPDBToGROMACS
-handleError $? "convertPDBToGROMACS"
-
 defineSimulationBox
-handleError $? "defineSimulationBox"
-
 solvateSystem
-handleError $? "solvateSystem"
-
 addIons
-handleError $? "addIons"
-
 energyMinimization
-handleError $? "energyMinimization"
-
 nvtEquilibration
-handleError $? "nvtEquilibration"
-
 nptEquilibration
-handleError $? "nptEquilibration"
-
 eliminateRestraints
-handleError $? "eliminateRestraints"
-
-#shortFreeMD
-#handleError $? "shortFreeMD"
+shortFreeMD
 
 echo "MD Preparation completed successfully."
